### ISSUE TITLE
SQL Syntax Error After Refreshing Signature Page

### ISSUE THREAD

**Issue by amydepalma** [mcipperly/rt.trkr8r.com#10]
Got the following error when I refreshed the Waiver page, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1"

URL I refreshed: http://amy.rt.trkr8r.com/signature.php?vid=16

**Comment by aquatopia** [comment]
Fixed in commit f0985a5.
