### ISSUE TITLE
reCAPTCHA

### ISSUE THREAD

**Issue by aquatopia** [mcipperly/rt.trkr8r.com#113]
"ERROR: Invalid domain for site key" appears on register.php, on the live production version

**Comment by aquatopia** [comment]
Uh, for the live production version obvs

**Comment by aquatopia** [comment]
I was still given a success message and returned to the homepage when clicking 'submit'

**Comment by mcipperly** [comment]
This should be corrected for volunteer.rtpittsburgh.org, I'll open a new bug (#114) for modifying the installation for future reCAPTCHA users on different domains.
