### ISSUE TITLE
Implement Merge Volunteers feature

### ISSUE THREAD

**Issue by mcipperly** [mcipperly/rt.trkr8r.com#121]
Implement feature to merge volunteers by email address - example, new email address, registered for multiple events with different email addresses, etc.

**Comment by amydepalma** [comment]
Requested by HIllary, "I know I mentioned it to you before, but I think it would be helpful so we can combine people who accidently sign up with two different emails"

**Comment by amydepalma** [comment]
We will create a new sidebar item, called "Manage Volunteers", where admins can look up volunteers by name. The search results will display below with their name,  email, phone number, print icon, and checkbox for merging.

> Print -> Name -> Email -> Phone -> Checkbox

Users can select 2 or more volunteers and then click a button saying "Merge Volunteer Records". A model will popup, confirming and letting them know this cannot be undone.

> Are you sure? Merging volunteer records cannot be undone.
