### ISSUE TITLE
Ability to delete events

### ISSUE THREAD

**Issue by amydepalma** [mcipperly/rt.trkr8r.com#123]
Requested by Hillary,  It would also be great if we could delete events. Right now there are the two test events, which I don’t think we necessarily need (unless you think so, then they can absolutely stay) and would love to remove them so when we pull data it doesn’t show us that stuff. We also, unfortunately, occasionally have volunteer events that get cancelled, so I would love to be able to remove those from the system if/when that happens."

**Comment by mcipperly** [comment]
Delete event now complete
