### ISSUE TITLE
Create Custom CSV File

### ISSUE THREAD

**Issue by amydepalma** [mcipperly/rt.trkr8r.com#13]
We currently have three files for this and I am not sure which is the correct one:

![image](https://cloud.githubusercontent.com/assets/11203848/8289050/f8623236-18e7-11e5-9635-fab2dc664106.png)

In the end, we need to rename the final file to "export-records.php" to match the admin naming. Can one of you let me know which to move forward with? I am pretty sure it's "custom-csv.php" but just want to confirm before renaming anything. 

I'm hoping to get this done for Wednesday's meeting.

Also, as a tangent, we should probably setting on a naming convention. Looks like we mostly use hyphens between words in file names, so we should probably stick with that.

Thanks!

**Comment by aquatopia** [comment]
the one with the hyphen, as far as I can tell, is the only one linked to in
another page.

**Comment by amydepalma** [comment]
Thanks! I deleted the extra page in commit #99714f7.
