### ISSUE TITLE
Edit Volunteers

### ISSUE THREAD

**Issue by mcipperly** [mcipperly/rt.trkr8r.com#134]
Ability to save edited volunteer profile information in the administrative console

**Comment by mcipperly** [comment]
@aquatopia I think we still need an update_volunteers for the db, I can give it a shot at some point unless you have something in mind already

**Comment by aquatopia** [comment]
I'll take a look at it this evening or this weekend.

**Comment by aquatopia** [comment]
I think what you're looking for is the add_form_responses function.  It's the one used when the volunteer fills out this info and it should work in this instance too.
