### ISSUE TITLE
Error on Check In button from Onsite Mode

### ISSUE THREAD

**Issue by amydepalma** [mcipperly/rt.trkr8r.com#17]
Got this error:

![image](https://cloud.githubusercontent.com/assets/11203848/8297169/7345745a-1928-11e5-9e5a-f665e691aa74.png)

However, I am pretty sure it's related to what Rob talked about on Saturday about old data being in there. I wanted to throw it up here just in case though.

I DID NOT get this error when I duplicated my actions using an email I entered earlier today.

**Comment by aquatopia** [comment]
No that's correct; it's caused by trying to make a query with a state
abbreviation ("PA") in place of whatever id number represents that state

**Comment by amydepalma** [comment]
Awesome. Thought so. Thanks! :)
