### ISSUE TITLE
Multiple Organizations - Export Records

### ISSUE THREAD

**Issue by mcipperly** [mcipperly/rt.trkr8r.com#22]
Implement filtering capability on record export page:
- Generate appropriate inputs based on data type
- Allow selection based on event as drop-down
- AND with existing date range

**Comment by amydepalma** [comment]
The design aspect of this is complete. Rob now needs to do his magic to make it work!

**Comment by amydepalma** [comment]
The toggle functionality has been completed for this. The Export by Org is the last bit to do before this is completed.

**Comment by aquatopia** [comment]
The functionality to filter by a _single_ organization is in place, but the ability to filter by multiple orgs (A or B or C) isn't yet implemented.
