### ISSUE TITLE
Youth/Minor Form Handling

### ISSUE THREAD

**Issue by mcipperly** [mcipperly/rt.trkr8r.com#25]
Implement handling of <18 y/o volunteers:
- Same form as normal flow, deviates on submit based on age
- Printable pre-filled parental signature wavier
- On-site mode
  - Two signature boxes for if parent is present and no pre-reg?
  - Handling signature from minor on-site
    - On-site supervisor approval?
  - Still need to have minor sign, that's how we consider someone as having volunteered

**Comment by aquatopia** [comment]
This functionality has been reduced to just having a link to a static form for the underaged user to print and bring to the event

**Comment by aquatopia** [comment]
Better represented by #83
