### ISSUE TITLE
Events - End-of-day Tasks

### ISSUE THREAD

**Issue by mcipperly** [mcipperly/rt.trkr8r.com#28]
Hour logging console for end-of-day (EOD) tasks:
- Display all volunteers who participated in a given event
  - Based on signatures in a day
- Allow logging of hours
- Allow assignment of organization within EOD screen
- Individual & Bulk assignment of orgs and hours 
  - Javascript to set fields in bulk without submitting, allowing easy individual org/hours assignment for one-off users?

**Comment by amydepalma** [comment]
The design aspect of this is complete. The three pages (event_completed, event_action, and event_noaction) represent demo pages for an event's detail page. They represent how each event state should look.
