### ISSUE TITLE
Organizations - Management

### ISSUE THREAD

**Issue by mcipperly** [mcipperly/rt.trkr8r.com#38]
Create/edit organizations via admin console

**Comment by amydepalma** [comment]
I created a Manage Orgs page and added a sidebar link

**Comment by amydepalma** [comment]
We need to update the Create Organization page to include inputs for Contact Name, COntact Details, and Organization Details:

![image](https://cloud.githubusercontent.com/assets/11203848/10036018/fe2dff36-616e-11e5-9a83-420511a91cba.png)

**Comment by amydepalma** [comment]
We need to make "Edit" button functional:
![image](https://cloud.githubusercontent.com/assets/11203848/10036030/27537378-616f-11e5-9773-04ebcc3002e3.png)

**Comment by amydepalma** [comment]
Fixed via #111
