### ISSUE TITLE
"Make Changes" button from Sign Waiver Page Doesn't Work

### ISSUE THREAD

**Issue by amydepalma** [mcipperly/rt.trkr8r.com#9]
I checked in using "amy@amymade.net" so all my info was there and I wanted to make a change, however, when I click the "Make Changes" button, I am directed to an empty page.

The page I was directed to was: http://amy.rt.trkr8r.com/register.php?edit=1&email=amy@amymade.net

**Comment by mcipperly** [comment]
This has a security implication, namely being able to get someone's full info from using their email address as a key. The current implementation only populates the email address on the make changes button, and does so using the value from the request; we should be able to make this populate everything when mode is onsite or higher.
